### ISSUE TITLE
Panic when attempting to insert a character when the editor buffer is full

### ISSUE THREAD

**Issue by mchesser** [dotcypress/ushell#1]
Hi, I'm not sure about the maintenance status of this crate, but I hit a panic when experimenting with one of the examples from the `stm32f4xx-hal` crate, so I thought I would still report it.

If the editor buffer is full, and the cursor is not at the end of the buffer, then the firmware will panic when it attempts to [insert the character into the editor buffer](https://github.com/dotcypress/ushell/blob/cbcd7facb1abfa2712a17199400f0debc6649994/src/shell.rs#L189).

I think the fix is probably to update the if statement here: https://github.com/dotcypress/ushell/blob/cbcd7facb1abfa2712a17199400f0debc6649994/src/shell.rs#L184 to also check whether `self.editor_len == self.editor_buf.len()`

**Comment by dotcypress** [comment]
@mchesser thank you for reporting this. 👍
Next release will have fixes for this issue.
